#!/usr/bin/env bash

# Trap CTRL-C to avoid background processes running
trap ctrl_c INT
ctrl_c() {
  # Clean the system
  kill -9 "$(pgrep 'sima')" >/dev/null 2>&1
  kill -9 "$(pgrep 't_graph')" >/dev/null 2>&1
  sync
  exit -2
}
kill -9 "$(pgrep 'sima')" >/dev/null 2>&1
kill -9 "$(pgrep 't_graph')" >/dev/null 2>&1

# Init vars
HOST="localhost"
# HARDCODED to reduce RAM impact all data is passed by pointers
NLP=1
SLP=1
POSITIONAL=()
while [[ $# -gt 0 ]]; do
  key="$1"

  case $key in
  -n | --nodes)
    TOT_SMH="$2"
    shift # past argument
    shift # past value
    ;;
  -d | --debug)
    DEBUG="$2"
    echo "Debug value $DEBUG"
    shift
    shift
    ;;
  *) # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift              # past argument
    ;;
  esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

if [[ -n $1 || -z ${TOT_SMH} ]]; then
  echo "Illegal number of parameters"
  echo "USAGE: ./run --nodes|-n #SMH [--debug|-d DEBUGCMD]"
  echo -e "\\t#SMH\\ttotal number of nodes to simulate"
  echo -e "\\t[DEBUGCMD] used for injecting *trace commands (optional)"
  exit -1
fi

rm ./*.finished

source ./scripts_configuration.sh
make clean
make

# Set sim parameters
export MIGRATION=0
export MFACTOR=1.2
export LOAD=0
export END_CLOCK=20000 
export DATA_MULES=16
export GRID_LENGTH=1000
export COMMUNICATION_DISTANCE=10
export MOBILITY_TYPE=2
export MULE_RADIUS=40
export ISLAND_SIZE=20




# Partitioning the #SMH among the available LPs
SMH=$((TOT_SMH / NLP))

###########################################################################################


# Normal Run
if [[ -z "$TEST" ]]; then
  # SImulation MAnager (SIMA) execution
  echo "Start time: $(date)"
  if [ $HOST == "$HOSTNAME" ] || [ $HOST == "localhost" ]; then
    echo "Starting SIMA (waiting for $NLP LPs)..."
    ./sima "$NLP" &
  fi
  $DEBUG ./t_graph "$NLP" $SMH ${TRACE_DIRECTORY}/test_btc_ $P  > "testmob.txt"
  echo "End time: $(date)"
  exit -1
fi


: <<'END'
END
